spring.application.name=AI-agent-test
server.port=8080

spring.ai.model.chat=openai
spring.ai.model.embedding=openai
spring.ai.openai.api-key=${DASHSCOPE_API_KEY}
spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
spring.ai.openai.chat.options.model=qwen3.7-plus
spring.ai.openai.embedding.options.model=qwen3.7-text-embedding